### ISSUE TITLE
Error not properly handled

### ISSUE THREAD

**Issue by javier-serrano** [kenahrens/newrelic-pm2-plugin#2]
While using the plugin we are receiving an error:

TypeError: Cannot read property 'statusCode' of undefined

Pointing to: https://github.com/kenahrens/newrelic-pm2-plugin/blob/master/pm2plugin.js#L99

This is causing the plugin to crash.

Can I submit a PR ?

**Comment by kenahrens** [comment]
@javier-serrano - let me look into this. Just curious, how are you running pm2plugin.js? Are you using a launcher like forever or PM2 itself, or just running from the command line?

**Comment by kenahrens** [comment]
@javier-serrano - can you try the latest version 1.0.3 to see if this fixes the issue? I adjusted the logic to check for the error first because if there's an error then httpResponse will be undefined and cause the error you showed.

**Comment by javier-serrano** [comment]
That's exactly the change I wanted to propose, we were getting undefined in httpResponse object.
Will let you know how it goes.

Thanks for fast response

**Comment by kenahrens** [comment]
Fixed in 1.0.3
